name: climb_around
description: "Climb around app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.5
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.3

# Run "flutter pub run flutter_launcher_icons"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
    - assets/climbing_spots.json
